// Original review snippets composed at seed time. Each review is generated by
// combining a positive opener, a service-specific body, and a closer. Mostly 5-star
// to feel realistic, with a long tail of lower ratings.

export const reviewAuthors: { name: string; city?: string }[] = [
  { name: "Sarah K.", city: "Houston" },
  { name: "Marcus T.", city: "Austin" },
  { name: "Priya R.", city: "Plano" },
  { name: "Jose M.", city: "San Antonio" },
  { name: "Ashley B.", city: "Dallas" },
  { name: "Tomás G.", city: "El Paso" },
  { name: "Becca H.", city: "Fort Worth" },
  { name: "Derek P.", city: "Arlington" },
  { name: "Lupita V.", city: "Corpus Christi" },
  { name: "Henry F.", city: "Houston" },
  { name: "Megan O.", city: "Frisco" },
  { name: "Ravi S.", city: "Irving" },
  { name: "Cassidy D.", city: "Round Rock" },
  { name: "Nathan A.", city: "McKinney" },
  { name: "Olivia W.", city: "Garland" },
  { name: "Pete L.", city: "Tyler" },
  { name: "Tara N.", city: "Lubbock" },
  { name: "Valerie J.", city: "Waco" },
  { name: "Will C.", city: "Amarillo" },
  { name: "Yusuf E.", city: "Dallas" },
  { name: "Zoe I.", city: "Austin" },
  { name: "Brendan Q.", city: "Houston" },
  { name: "Imani F.", city: "Plano" },
  { name: "Kendrick R.", city: "Fort Worth" },
];

export const positiveOpeners: string[] = [
  "Couldn't be happier with the work.",
  "Really professional from start to finish.",
  "Best experience I've had with a contractor in years.",
  "These guys did everything they said they would.",
  "Genuinely impressed.",
  "Showed up exactly when they said they would.",
  "Saved me from a much bigger problem.",
  "Quote was fair and the work was clean.",
  "Will use them again without question.",
  "Top-notch service all around.",
  "On time, on budget, no surprises.",
  "Best money I've spent on the house in a long time.",
];

export const neutralOpeners: string[] = [
  "Mostly a good experience, with one or two hiccups.",
  "Did the job, but it wasn't perfect.",
  "Solid work overall — a few small things to call out.",
  "Pretty good value, just don't expect hand-holding.",
];

export const negativeOpeners: string[] = [
  "Disappointed in how this went.",
  "Wouldn't book them again.",
  "Job was finished but the experience wasn't great.",
];

// Service-specific bodies keyed by category slug
export const serviceBodies: Record<string, string[]> = {
  plumbing: [
    "Diagnosed a slab leak that two other companies misdiagnosed — saved us thousands.",
    "Swapped our 50-gallon for a tankless in a single day, including the new gas line.",
    "Cleared a 30-foot mainline blockage and ran a camera so we could see the root intrusion ourselves.",
    "Installed three new fixtures and a pressure regulator. Everything's quieter than it's been in years.",
    "Found the leak under the slab fast and patched the supply line cleanly.",
    "Repipe took three days, the crew was tidy, and they patched every hole they cut.",
  ],
  hvac: [
    "AC died in July. They had a tech here in three hours and a new system in two days.",
    "Diagnosed a dying capacitor on the first visit and didn't try to upsell us a new unit.",
    "Installed a 16 SEER2 and the upstairs is finally cool.",
    "Tune-up was thorough — they cleaned the coils, checked refrigerant, and walked me through the readings.",
    "Replaced our duct system and our utility bill dropped about 18% the next month.",
    "Showed up before sunrise to a no-cool call. Compressor was shot but they had the part on the truck.",
  ],
  electrical: [
    "Upgraded our 100A panel to 200A, pulled the permit, and got it inspected within a week.",
    "Installed a Level 2 EV charger in the garage and balanced the load properly.",
    "Tracked down a tripping breaker that nobody else could find. Turned out to be a cooked outlet upstream.",
    "Whole-home generator transfer switch — clean job, neatly labeled.",
    "Added six recessed lights and a fan in our family room. Drywall patches were unnoticeable.",
  ],
  roofing: [
    "Hail came through and they had a tarp on within four hours.",
    "Full roof replacement in two days. Yard was cleaner when they left than when they arrived.",
    "Worked directly with our adjuster — we didn't have to chase paperwork.",
    "Caught some shady damage from a previous repair attempt and documented everything.",
    "Class 4 impact-rated shingles and the warranty is transferable.",
  ],
  "foundation-repair": [
    "Engineer report came in, we did 14 piers, and the doors swing right again.",
    "They corrected our drainage issue on the same trip — no upselling.",
    "Transferable warranty and the price held to the original quote.",
    "Crew was respectful of the lawn and patched the dig sites well.",
    "Proper steel piers, not the press-board nonsense one of their competitors quoted.",
  ],
  "pest-control": [
    "Quarterly plan has kept the German roaches out for over a year.",
    "Treated for fire ants in the spring and we didn't see a mound all summer.",
    "Termite warranty was transferable when we sold — saved us a haggle at closing.",
    "Killed our wasp problem on a same-day call.",
    "Rodent exclusion work was thorough — sealed entry points we hadn't even noticed.",
  ],
  "lawn-care": [
    "Lawn looks better than the neighbors' for the first time ever.",
    "Caught a sprinkler head shooting onto the driveway and fixed it without charging extra.",
    "Reseeded our weak spots in the fall and they're filling in great.",
    "Pre-emergent in February kept the crabgrass at bay all year.",
    "Crew is consistent and the schedule never slips.",
  ],
  "tree-service": [
    "Big oak limb came down in a storm — they had it cleared by lunch.",
    "Took down a 60-footer that was leaning toward the house. No damage to anything.",
    "Stump grind was below grade and they hauled the chips for free.",
    "Pruned three large oaks — the canopy looks balanced and healthy now.",
  ],
  "pool-service": [
    "Weekly chemistry has the pool looking the best it has in five years.",
    "Replaced our pump with a variable speed in a single afternoon.",
    "Swapped to salt and the water feels completely different.",
    "Found a leak in the skimmer line we'd been chasing for months.",
  ],
  cleaning: [
    "Two-person team, three hours, the place sparkles.",
    "Move-out clean was so thorough we got our full deposit back.",
    "Bring their own supplies and ask if I want anything switched out.",
    "Same team every visit — they actually know our place.",
  ],
  painting: [
    "Prep was thorough — caulked every gap, primed every patch.",
    "Three colors throughout the downstairs and not a drop on the floors or trim.",
    "Cabinets came out so smooth they look factory-finished.",
    "Exterior repaint with a full power-wash and the color held all summer.",
  ],
  handyman: [
    "Mounted three TVs and ran the cables through the walls in two hours.",
    "Knocked out my entire honey-do list in one afternoon.",
    "Fixed a sticking door, swapped a faucet, and re-caulked the tub.",
    "Texted me a quote first, finished within the time they said.",
  ],
  flooring: [
    "Whole downstairs in LVP, including transitions and quarter round. Looks great.",
    "Refinished the hardwoods and they look brand new.",
    "Tiled our master bath — every grout line is straight as an arrow.",
  ],
  windows: [
    "Eight windows replaced in two days. Caulking was tidy and the trim is clean.",
    "House is noticeably quieter and our gas bill dropped.",
  ],
  siding: [
    "Replaced our wood siding with fiber cement. Took a week, looks fantastic.",
    "Color held perfectly through a hot summer.",
  ],
  gutters: [
    "Seamless gutters with leaf guards — I haven't had to clean them once.",
    "Re-pitched the gutters that the original builder put in wrong.",
  ],
  "garage-doors": [
    "Spring snapped at 7 a.m., they had a tech out by 10 with the right size on the truck.",
    "New opener is whisper quiet and works with my phone.",
  ],
  locksmith: [
    "Rekeyed the whole house the day we closed.",
    "Locked out at 11 p.m. — they showed up in 25 minutes.",
  ],
  "appliance-repair": [
    "Fridge was warming up — they replaced the compressor that day with a part from the truck.",
    "Dryer was making a screech, they had the belt and the rollers in stock.",
  ],
  fence: [
    "Cedar privacy with metal posts — should outlast my ownership.",
    "Wrought-iron pool fence looks great and meets code.",
  ],
  "deck-patio": [
    "Composite deck with cable rail. Designer stage was great, build was clean.",
    "Screened-in patio means we can use the backyard in summer again.",
  ],
  concrete: [
    "Tore out the old driveway and poured 4,000 PSI with proper joints.",
    "Stamped concrete patio looks nicer than the photos in their portfolio.",
  ],
  solar: [
    "8.4 kW system plus a Powerwall — the install team was professional all the way through.",
    "Bills have averaged near zero since we turned the system on.",
  ],
  "mosquito-control": [
    "Patio is finally usable in July. Three-week service has been worth every dollar.",
    "Misting system runs at dusk and dawn — no more bites.",
  ],
  "junk-removal": [
    "Cleared out the entire garage in 90 minutes.",
    "Hauled away a treadmill and an old fridge same day.",
  ],
  moving: [
    "Three movers, eight hours, no dings on the furniture.",
    "Packed our kitchen carefully — not a single broken plate.",
  ],
  remodeling: [
    "Full kitchen remodel finished on time and within $400 of the original quote.",
    "Master bath came out exactly like the design renders.",
  ],
  drywall: [
    "Patched four ceiling holes from old leaks — texture matches perfectly.",
    "Hung and finished an entire bonus room in a week.",
  ],
  "water-damage": [
    "Slab leak flooded the ground floor — they had air movers running within hours and saved most of the flooring.",
    "Worked directly with insurance and we didn't have to argue with the adjuster.",
  ],
  septic: [
    "Pumped our 1,000-gallon tank and inspected the d-box. Easy and cheap.",
    "Aerobic system replacement, fully permitted with TCEQ.",
  ],
  "fire-ant-control": [
    "Yard-wide bait plus targeted mound treatment — no mounds for the rest of the season.",
    "Twice-yearly visits keep the colonies in check.",
  ],
  "storm-damage": [
    "Tarped the roof same-day after the hail event and queued us for a proper replacement.",
    "Adjuster meeting went smoothly because they had photos and reports ready.",
  ],
};

export const positiveClosers: string[] = [
  "Already booked them for the next project.",
  "Highly recommended.",
  "Will refer them to anyone who asks.",
  "Worth every dollar.",
  "Clear communication the whole way.",
  "These are the guys you want.",
];

export const neutralClosers: string[] = [
  "Solid overall — minor stuff to clean up.",
  "Would still book again.",
];

export const negativeClosers: string[] = [
  "Hoping next time goes better.",
  "Need to tighten up the communication.",
];
